import 'package:flutter/material.dart';

class Localization {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'live_tv': 'LIVE TV',
      'movies': 'MOVIES',
      'series': 'SERIES',
      'settings': 'SETTINGS',
      'logout': 'LOGOUT',
      'no_content': 'No content available',
      'error_loading': 'Error loading channels:',
      'language': 'Language',
      'theme': 'Theme Color',
      'startup_screen': 'Startup Screen',
      'hardware_decoding': 'Hardware Decoding',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'en': 'English',
      'ar': 'Arabic (العربية)',
      'ku': 'Kurdish Sorani (کوردی)',
      'amber': 'Amber',
      'red': 'Netflix Red',
      'blue': 'Neon Blue',
      'green': 'Emerald Green',
      'dashboard': 'Dashboard',
    },
    'ar': {
      'live_tv': 'البث المباشر',
      'movies': 'أفلام',
      'series': 'مسلسلات',
      'settings': 'الإعدادات',
      'logout': 'تسجيل خروج',
      'no_content': 'لا يوجد محتوى متاح',
      'error_loading': 'خطأ في تحميل القنوات:',
      'language': 'اللغة',
      'theme': 'لون السمة',
      'startup_screen': 'شاشة البدء',
      'hardware_decoding': 'فك تشفير الأجهزة',
      'enabled': 'مفعل',
      'disabled': 'معطل',
      'en': 'English',
      'ar': 'العربية',
      'ku': 'Kurdish Sorani (کوردی)',
      'amber': 'عنبري',
      'red': 'أحمر نتفليكس',
      'blue': 'أزرق نيون',
      'green': 'أخضر زمردي',
      'dashboard': 'لوحة القيادة',
    },
    'ku': {
      'live_tv': 'پەخشی ڕاستەوخۆ',
      'movies': 'فیلمەکان',
      'series': 'زنجیرەکان',
      'settings': 'ڕێکخستنەکان',
      'logout': 'چوونە دەرەوە',
      'no_content': 'هیچ ناوەڕۆکێک بەردەست نییە',
      'error_loading': 'هەڵە لە بارکردنی کەناڵەکان:',
      'language': 'زمان',
      'theme': 'ڕەنگی ڕووکار',
      'startup_screen': 'شاشەی دەستپێکردن',
      'hardware_decoding': 'خێراکردنی هاردوێر',
      'enabled': 'چالاککراوە',
      'disabled': 'ناچالاککراوە',
      'en': 'English',
      'ar': 'Arabic (العربية)',
      'ku': 'کوردی',
      'amber': 'کەھرەبایی',
      'red': 'سووری نێتفلێکس',
      'blue': 'شینی نیۆن',
      'green': 'سەوزی زمروت',
      'dashboard': 'داشبۆرد',
    }
  };

  static String t(String key, String langCode) {
    return _translations[langCode]?[key] ?? _translations['en']?[key] ?? key;
  }
}
